### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/BrokkR#26]
- [x] Vignette (example)
- [x] Installation in ReadMe
- [x] PkgDown
- [x] Double check documentation (each person checks their own)

**Comment by mikeguron** [comment]
We will need to add an option for out vignettes as described in the warning below:

Warning message:
The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "Example_Usage", and the latter is "Example Usage". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
